name: dot_cast
description: > 
  This package provides the user with extension methods for casting objects allowing
  you to write less and cleaner code.
version: 1.2.0
repository: https://github.com/SEGVeenstra/dot_cast

environment:
  sdk: '>=2.18.1 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
